In [52]:
import pandas as pd 
import numpy as np
import re
names=['wiki_ID','freebase_ID','name','release_date','revenue','runtime','languages','countries','genres']
movie_metadata=pd.read_csv('../Data/movie.metadata.tsv', sep='\t',names=names)
movie_metadata

,wiki_ID,freebase_ID,name,release_date,revenue,runtime,languages,countries,genres
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"
...,...,...,...,...,...,...,...,...,...
81736,35228177,/m/0j7hxnt,Mermaids: The Body Found,2011-03-19,NaN,120.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/07s9rl0"": ""Drama""}"
81737,34980460,/m/0g4pl34,Knuckle,2011-01-21,NaN,96.0,"{""/m/02h40lc"": ""English Language""}","{""/m/03rt9"": ""Ireland"", ""/m/07ssc"": ""United Ki...","{""/m/03bxz7"": ""Biographical film"", ""/m/07s9rl0..."
81738,9971909,/m/02pygw1,Another Nice Mess,1972-09-22,NaN,66.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/06nbt"": ""Satire"", ""/m/01z4y"": ""Comedy""}"
81739,913762,/m/03pcrp,The Super Dimension Fortress Macross II: Lover...,1992-05-21,NaN,150.0,"{""/m/03_9r"": ""Japanese Language""}","{""/m/03_3d"": ""Japan""}","{""/m/06n90"": ""Science Fiction"", ""/m/0gw5n2f"": ..."
81740,12476867,/m/02w7zz8,Spliced,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0d060g"": ""Canada""}","{""/m/01jfsb"": ""Thriller"", ""/m/03npn"": ""Horror""..."

In [57]:
# extracting a list of all countries of a movie from a string in the column 'countries' in movie_metadata
def extract_countries(string):
    between_quotes = re.findall(r'"(.*?)"', string) # extracting all words from the string that are between quotes
    for word in between_quotes:
        if word[0]=='/':
            between_quotes.remove(word) # removing all words between quotes that start with /, as they are not country names
    return between_quotes # we are left with only words corresponding to country names

In [58]:
# counting the number of countries of a movie from a string in the column 'countries' in movie_metadata
def count_countries(string):
    country_number=string.count(',') +1 # counting the number of comas in the string, as they are separators between different countries
    return country_number # the number of comas + 1 corresponds to the number of countries

In [62]:
movie_metadata['country_number']=movie_metadata['countries'].astype(str).apply(count_countries) # new column in movie_metadata with the number of countries for each film
movie_metadata['country_list']=movie_metadata['countries'].astype(str).apply(extract_countries) # new column in movie_metadata with a list of strings of all country names for each film

In [71]:
# creating a list of all country names of all films combined, to count the number of occurrences of each country
total_country_list=[]
for list in movie_metadata['country_list']: # iterating over the lists of countries for all films
    for element in list: # iterating over the countries in a given list of countries
        total_country_list.append(element) # adding each country name to the list of all countries
total_country_list=pd.DataFrame({'country':total_country_list})
country_distribution_df=total_country_list.value_counts().reset_index() # df of all countries and their number of occurrence in all films
country_distribution_df[country_distribution_df['count']>1000] # displaying only countries that are present in more than 1000 films

                     country  count
0   United States of America  34408
1                      India   8411
2             United Kingdom   7868
3                     France   4395
4                      Italy   3163
5                      Japan   2647
6                     Canada   2534
7                    Germany   2393
8                  Argentina   1468
9                  Hong Kong   1240
10                     Spain   1136
11                 Australia   1114