In [1]:
import pandas as pd 
import numpy as np

In [26]:
# source : https://ourworldindata.org/grapher/median-age?tab=table&time=earliest..2012&country=JPN~IND~GBR~USA~FRA~ITA~CAN~DEU~ARG~HKG~AUS~ESP
median_age=pd.read_csv('median-age.csv')
median_age.head()

,Entity,Code,Year,Median age - Sex: all - Age: all - Variant: estimates,Median age - Sex: all - Age: all - Variant: medium
0,Afghanistan,AFG,1950,18.395,NaN
1,Afghanistan,AFG,1951,18.370,NaN
2,Afghanistan,AFG,1952,18.333,NaN
3,Afghanistan,AFG,1953,18.289,NaN
4,Afghanistan,AFG,1954,18.239,NaN

In [27]:
# renaming the columns
median_age.columns=['Country','Code','Year','Median age', 'Median age prediction']

# removing rows corresponding to years after 2013
index=median_age[median_age['Year']>2013].index
median_age=median_age.drop(index)

# removing the 'Code' and 'Median age prediction' columns
median_age=median_age.drop('Code',axis=1)
median_age=median_age.drop('Median age prediction',axis=1)
median_age

           Country  Year  Median age
0      Afghanistan  1950      18.395
1      Afghanistan  1951      18.370
2      Afghanistan  1952      18.333
3      Afghanistan  1953      18.289
4      Afghanistan  1954      18.239
...            ...   ...         ...
38111     Zimbabwe  2009      17.363
38112     Zimbabwe  2010      17.284
38113     Zimbabwe  2011      17.186
38114     Zimbabwe  2012      17.032
38115     Zimbabwe  2013      16.867

[16192 rows x 3 columns]

In [34]:
dict_us={'United States': median_age[median_age['Country']=='United States']['Median age']}
df_us=pd.DataFrame(dict_us)
df_us

       United States
35938         28.962
35939         28.993
35940         29.020
35941         29.031
35942         29.018
...              ...
35997         35.817
35998         35.920
35999         36.008
36000         36.090
36001         36.175

[64 rows x 1 columns]

In [42]:
# creating a df of the median age between 1950 and 2013, for the 11 countries with more than 1000 films in the database
country_list=['United States', 'India', 'United Kingdom', 'France', 'Italy', 'Japan', 'Canada', 'Germany', 'Argentina', 'Hong Kong', 'Spain', 'Australia']
dict_countries={}
for country in ['United States', 'India', 'United Kingdom', 'France', 'Italy', 'Japan', 'Canada', 'Germany', 'Argentina', 'Hong Kong', 'Spain', 'Australia']:
    dict_countries[country]=median_age[median_age['Country']==country]['Median age'].tolist() # extracting the median age data for the given country
countries_df=pd.DataFrame(dict_countries)
years_df=pd.DataFrame(median_age[median_age['Country']=='Afghanistan']['Year']) # extracting the column year
median_age_df=pd.concat([years_df,countries_df],axis=1) # creating a df with a column for the year and a column for each country
median_age_df

,Year,United States,India,United Kingdom,France,Italy,Japan,Canada,Germany,Argentina,Hong Kong,Spain,Australia
0,1950,28.962,20.015,33.889,33.441,27.547,21.311,26.668,32.919,24.374,22.802,26.475,29.384
1,1951,28.993,19.978,33.908,32.442,27.846,21.493,26.657,32.815,24.501,22.865,26.763,29.294
2,1952,29.020,19.935,33.900,31.782,28.180,21.739,26.604,32.632,24.638,22.911,26.994,29.268
3,1953,29.031,19.874,33.834,31.673,28.534,22.029,26.535,32.693,24.779,22.929,27.222,29.252
4,1954,29.018,19.801,33.886,31.717,28.880,22.364,26.445,32.929,24.920,22.937,27.453,29.215
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2009,35.817,23.342,38.057,38.791,42.164,43.880,38.542,42.920,28.659,39.488,38.754,35.914
60,2010,35.920,23.641,38.191,39.013,42.513,44.240,38.740,43.265,28.874,39.916,39.182,36.043
61,2011,36.008,23.949,38.333,39.262,42.877,44.539,38.937,43.632,29.081,40.328,39.634,36.179
62,2012,36.090,24.265,38.489,39.518,43.238,44.808,39.124,44.076,29.290,40.674,40.109,36.234
63,2013,36.175,24.588,38.629,39.773,43.598,45.099,39.297,44.487,29.492,40.998,40.630,36.242

for